# Generated by Django 5.0.3 on 2024-03-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0002_bookinventory_created_at_bookinventory_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pandhamtarget',
            old_name='group',
            new_name='pandham_target_group',
        ),
        migrations.AlterField(
            model_name='propagation',
            name='book_inventroy',
            field=models.ForeignKey(help_text='Select the Pandham book.', on_delete=django.db.models.deletion.CASCADE, related_name='Propagation', to='pandham.bookinventory', verbose_name='Pandham Book'),
        ),
    ]
