# Generated by Django 5.0.3 on 2024-03-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0003_rename_group_pandhamtarget_pandham_target_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='pandhamstock',
            options={'verbose_name': 'Pandham Stock ', 'verbose_name_plural': 'Pandham Stock  '},
        ),
        migrations.AlterModelOptions(
            name='propagation',
            options={'verbose_name': 'Propagation', 'verbose_name_plural': 'Propagation'},
        ),
        migrations.AddField(
            model_name='propagation',
            name='receive_book',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of books received'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='donate_book',
            field=models.PositiveIntegerField(default=0, help_text='Request PTF to distribute books to suitable recipients', verbose_name='Number of books for donation'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='transaction_type',
            field=models.CharField(choices=[('contribute', 'Contribute to the Dhamma publishing fund and receive book or donate them as Pandham.'), ('request', 'Request Pandham books for self study.')], default='contribute', max_length=20, verbose_name='Choose an Action'),
        ),
    ]
