# Generated by Django 5.0.3 on 2024-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0004_alter_bookinventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinventory',
            name='sequence_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequence Order'),
        ),
    ]
