# Generated by Django 5.0.3 on 2024-03-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0005_bookinventory_sequence_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinventory',
            options={'ordering': ['sequence_order', 'book_name'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
    ]
