# Generated by Django 5.0.3 on 2024-03-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0008_remove_inventorytransaction_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='updated_by',
        ),
    ]
