# Generated by Django 5.0.3 on 2024-03-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0009_remove_inventorytransaction_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='transaction_date',
        ),
    ]
