# Generated by Django 5.0.3 on 2024-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0010_remove_inventorytransaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='propagation',
            name='request_rejected',
            field=models.BooleanField(default=False, help_text='Check this box if the request is rejected.', verbose_name='Request Rejected'),
        ),
    ]
