# Generated by Django 5.0.3 on 2024-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0011_propagation_request_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propagation',
            name='request_rejected',
        ),
        migrations.AlterField(
            model_name='propagation',
            name='shipping_address',
            field=models.TextField(help_text='Enter the shipping address and receiver contact number.', null=True, verbose_name='Shipping Address'),
        ),
    ]
