# Generated by Django 5.0.3 on 2024-03-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0012_remove_propagation_request_rejected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propagation',
            old_name='donate_book',
            new_name='donate_books',
        ),
        migrations.RenameField(
            model_name='propagation',
            old_name='receive_book',
            new_name='receive_books',
        ),
    ]
