# Generated by Django 5.0.3 on 2024-03-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0013_rename_donate_book_propagation_donate_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandhamstock',
            name='book_inventroy',
        ),
        migrations.AddField(
            model_name='pandhamstock',
            name='book_inventory',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='pandham.bookinventory', verbose_name='Book'),
            preserve_default=False,
        ),
    ]
