# Generated by Django 5.0.3 on 2024-03-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0014_remove_pandhamstock_book_inventroy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorytransaction',
            old_name='book_inventroy',
            new_name='book_inventory',
        ),
        migrations.RenameField(
            model_name='propagation',
            old_name='book_inventroy',
            new_name='book_inventory',
        ),
    ]
