# Generated by Django 5.0.3 on 2024-03-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0015_rename_book_inventroy_inventorytransaction_book_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propagation',
            name='payment_notified',
            field=models.BooleanField(default=False, verbose_name='Payment Notified'),
        ),
        migrations.AddField(
            model_name='propagation',
            name='proof_of_payment',
            field=models.ImageField(default=False, help_text='Upload the proof of payment.', upload_to='proof_of_payment', verbose_name='Proof of Payment'),
            preserve_default=False,
        ),
    ]
