# Generated by Django 5.0.3 on 2024-03-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0016_propagation_payment_notified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propagation',
            old_name='request_books',
            new_name='requested',
        ),
        migrations.RemoveField(
            model_name='propagation',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='propagation',
            name='proof_of_payment',
            field=models.ImageField(blank=True, help_text='Upload the proof of payment.', null=True, upload_to='proof_of_payment', verbose_name='Proof of Payment'),
        ),
        migrations.CreateModel(
            name='RequestPandham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_books', models.PositiveIntegerField(default=1, help_text='Calculated as the number of books.', verbose_name='Quantity')),
                ('shipping_address', models.TextField(help_text='Enter the shipping address and receiver contact number.', null=True, verbose_name='Shipping Address')),
                ('name', models.CharField(default='Anonymous', help_text='Please specify name, pseudonym, or dedication.', max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(help_text='Contactable mobile phone number ie.0988888888 (not publicly disclosed).', max_length=20, verbose_name='Phone Number')),
                ('otp', models.CharField(help_text='Enter the OTP number.', max_length=6, verbose_name='OTP')),
                ('date_request', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_inventory', models.ForeignKey(help_text='Select the Pandham book.', on_delete=django.db.models.deletion.CASCADE, related_name='request_propagation', to='pandham.bookinventory', verbose_name='Pandham Book')),
                ('propagation', models.ForeignKey(blank=True, help_text='Reference to the support publication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_propagation', to='pandham.propagation', verbose_name='Reference')),
                ('target_groups', models.ManyToManyField(blank=True, help_text='Select the target groups for this support publication.', to='pandham.pandhamtargetgroup', verbose_name='Target Groups')),
            ],
            options={
                'verbose_name': 'Request Pandham',
                'verbose_name_plural': 'Request Pandham',
            },
        ),
    ]
