# Generated by Django 5.0.3 on 2024-03-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0017_rename_request_books_propagation_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpandham',
            name='target_groups',
        ),
        migrations.AddField(
            model_name='requestpandham',
            name='recipient_category',
            field=models.ManyToManyField(blank=True, help_text='Please specify the group or category you or your organization belongs to.', to='pandham.pandhamtargetgroup', verbose_name='Recipient Category'),
        ),
    ]
