# Generated by Django 5.0.3 on 2024-03-17 14:15

import coderedcms.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0018_remove_requestpandham_target_groups_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pandhamstock',
            options={'verbose_name': 'Padham Stock', 'verbose_name_plural': 'Padham Stock'},
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='book_name',
            field=models.CharField(max_length=255, verbose_name='ชื่อหนังสือ'),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_cover', to='wagtailimages.image', verbose_name='ปกหนังสือ'),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='จำนวนหนังสือคงเหลือ'),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='description',
            field=coderedcms.fields.CoderedStreamField(blank=True, use_json_field=True, verbose_name='รายละเอียดเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='initial_stock',
            field=models.IntegerField(default=0, verbose_name='จำนวนหนังสือเริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='พร้อมใช้งาน'),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='minimum_stock_level',
            field=models.IntegerField(default=0, verbose_name='ระดับสต็อกขั้นต่ำ'),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ราคา'),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='sequence_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ลำดับ'),
        ),
        migrations.AlterField(
            model_name='bookinventory',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='รายละเอียดย่อ'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='book_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pandham.bookinventory', verbose_name='หนังสือ'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='details',
            field=models.TextField(blank=True, help_text='ระบุรายละเอียดเฉพาะเกี่ยวกับธุรกรรมนี้', verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.IntegerField(verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'นำเข้าคลัง'), ('pandham', 'เพิ่มคลังปันธรรม'), ('support', 'สนับสนุนการพิมพ์'), ('request', 'ขอรับปันธรรม'), ('adjustment', 'ปรับปรุงยอดหนังสือ')], max_length=255, verbose_name='ประเภทธุรกรรม'),
        ),
        migrations.AlterField(
            model_name='pandhamstock',
            name='book_inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='pandham.bookinventory', verbose_name='หนังสือ'),
        ),
        migrations.AlterField(
            model_name='pandhamstock',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='จำนวนหนังสือคงเหลือ'),
        ),
        migrations.AlterField(
            model_name='pandhamstock',
            name='initial_stock',
            field=models.IntegerField(default=0, verbose_name='จำนวนหนังสือเริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='amount_contributed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ร่วมบริจาคเงินสนับสนุนกองทุนการพิมพ์หนังสือ', max_digits=10, verbose_name='สมทบทุนการพิมพ์'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='book_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Propagation', to='pandham.bookinventory', verbose_name='หนังสือ'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='date_contribute',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='donate_books',
            field=models.PositiveIntegerField(default=0, help_text='มอบหนังสือให้กับมูลนิธิฯ ช่วยจัดสรรแก่ผู้รับที่เหมาะสม', verbose_name='จำนวนเล่มที่ต้องการปันธรรม'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='ดำเนินการเสร็จสิ้น'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='name',
            field=models.CharField(default='ไม่ประสงค์ออกนาม', help_text='กรุณาระบุชื่อ ฉายา นามแฝง หรือคำอุทิศ', max_length=255, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='note',
            field=models.TextField(blank=True, help_text='บันทึกหรือโน้ตสำหรับธุรกรรมนี้', null=True, verbose_name='บันทึกหรือโน้ต'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='number_of_books',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='otp',
            field=models.CharField(help_text='กรอกรหัส OTP', max_length=6, verbose_name='รหัส OTP'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='payment_notified',
            field=models.BooleanField(default=False, verbose_name='แจ้งชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='phone_number',
            field=models.CharField(help_text='หมายเลขโทรศัพท์ที่สามารถติดต่อได้ เช่น 0988888888 (ไม่เปิดเผยต่อสาธารณะ)', max_length=20, verbose_name='หมายเลขโทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='proof_of_payment',
            field=models.ImageField(blank=True, help_text='อัปโหลดหลักฐานการชำระเงิน', null=True, upload_to='proof_of_payment', verbose_name='หลักฐานการชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='receive_books',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนเล่มที่ต้องการรับ'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='requested',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนเล่มที่ปันธรรมแล้ว'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='shipping_address',
            field=models.TextField(help_text='กรอกที่อยู่ในการจัดส่ง และหมายเลขโทรศัพท์ติดต่อผู้รับ', null=True, verbose_name='ที่อยู่ในการจัดส่ง'),
        ),
        migrations.AlterField(
            model_name='propagation',
            name='target_groups',
            field=models.ManyToManyField(blank=True, to='pandham.pandhamtargetgroup', verbose_name='กลุ่มเป้าหมาย'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='book_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_propagation', to='pandham.bookinventory', verbose_name='หนังสือ'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='date_request',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='เสร็จสิ้น'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อ นามสกุล หรือ ฉายา (พระภิกษุ)'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='number_of_books',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='otp',
            field=models.CharField(help_text='กรอกรหัส OTP', max_length=6, verbose_name='รหัส OTP'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='phone_number',
            field=models.CharField(help_text='หมายเลขโทรศัพท์ที่สามารถติดต่อได้ เช่น 0988888888 (ไม่เปิดเผยต่อสาธารณะ)', max_length=20, verbose_name='หมายเลขโทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='propagation',
            field=models.ForeignKey(blank=True, help_text='อ้างอิงรายการสนับสนุนการพิมพ์', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_propagation', to='pandham.propagation', verbose_name='อ้างอิง'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='recipient_category',
            field=models.ManyToManyField(blank=True, help_text='กรุณาระบุกลุ่มหรือองค์กรของคุณ', to='pandham.pandhamtargetgroup', verbose_name='กลุ่ม'),
        ),
        migrations.AlterField(
            model_name='requestpandham',
            name='shipping_address',
            field=models.TextField(help_text='กรอกที่อยู่ในการจัดส่งและหมายเลขติดต่อของผู้รับ', null=True, verbose_name='ที่อยู่ในการจัดส่ง'),
        ),
    ]
