# Generated by Django 5.0.3 on 2024-03-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0019_alter_pandhamstock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpandham',
            name='date_request',
        ),
        migrations.AddField(
            model_name='requestpandham',
            name='is_waiting',
            field=models.BooleanField(default=False, verbose_name='รอปันธรรม'),
        ),
    ]
