# Generated by Django 5.0.3 on 2024-03-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0020_remove_requestpandham_date_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propagation',
            name='target_groups',
            field=models.ManyToManyField(null=True, to='pandham.pandhamtargetgroup', verbose_name='กลุ่มเป้าหมาย'),
        ),
    ]
