# Generated by Django 5.0.3 on 2024-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0022_alter_propagation_number_of_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propagation',
            name='target_groups',
            field=models.ManyToManyField(blank=True, to='pandham.pandhamtargetgroup', verbose_name='กลุ่มเป้าหมาย'),
        ),
    ]
