# Generated by Django 5.0.3 on 2024-03-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0023_alter_propagation_target_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propagation',
            name='date_contribute',
        ),
    ]
