# Generated by Django 5.0.3 on 2024-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0024_remove_propagation_date_contribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='propagation',
            name='reference_number',
            field=models.CharField(default=20240319111111, editable=False, help_text='หมายเลขอ้างอิงสำหรับธุรกรรมนี้', max_length=20, unique=True, verbose_name='หมายเลขอ้างอิง'),
            preserve_default=False,
        ),
    ]
