# Generated by Django 5.0.3 on 2024-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0025_propagation_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propagation',
            name='reference_number',
            field=models.CharField(help_text='หมายเลขอ้างอิงสำหรับธุรกรรมนี้', max_length=20, unique=True, verbose_name='หมายเลขอ้างอิง'),
        ),
    ]
