# Generated by Django 5.0.3 on 2024-03-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0026_alter_propagation_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpandham',
            name='reference_number',
            field=models.CharField(default=20241119111111, help_text='หมายเลขอ้างอิงสำหรับธุรกรรมนี้', max_length=20, unique=True, verbose_name='หมายเลขอ้างอิง'),
            preserve_default=False,
        ),
    ]
