# Generated by Django 5.0.3 on 2024-03-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0027_requestpandham_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpandham',
            name='accept_terms',
            field=models.BooleanField(default=True, verbose_name='ยอมรับเงื่อนไขการรับหนังสือ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'นำเข้าคลัง'), ('pandham', 'เพิ่มคลังปันธรรม'), ('support', 'สนับสนุนการพิมพ์'), ('request', 'ขอรับปันธรรม'), ('donate', 'ปันธรรมโดยมูลนิธิฯ'), ('adjustment', 'ปรับปรุงยอด')], max_length=255, verbose_name='ประเภทธุรกรรม'),
        ),
    ]
