# Generated by Django 5.0.3 on 2024-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0028_requestpandham_accept_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinventory',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='คุณสมบัติเบื้องต้นของผู้สนใจศึกษาที่ควรมีก่อนอ่านหนังสือเล่มนี้', verbose_name='คุณสมบัติ'),
        ),
    ]
