# Generated by Django 5.0.3 on 2024-03-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0029_bookinventory_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinventory',
            name='prerequisites',
        ),
    ]
