# Generated by Django 5.0.3 on 2024-03-21 08:20

import coderedcms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0030_remove_bookinventory_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinventory',
            name='prerequisites',
            field=coderedcms.fields.CoderedStreamField(blank=True, help_text='คุณสมบัติเบื้องต้นของผู้สนใจศึกษาที่ควรมีก่อนอ่านหนังสือเล่มนี้', use_json_field=True, verbose_name='คุณสมบัติ'),
        ),
    ]
