# Generated by Django 5.0.3 on 2024-03-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0031_bookinventory_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpandham',
            name='accept_terms',
            field=models.BooleanField(default=False, verbose_name='ยอมรับเงื่อนไขการรับหนังสือ'),
        ),
    ]
